### ISSUE TITLE
`Unknown type name 'FOUNDATION_EXPORT'` when building EmitterKit.h

### ISSUE THREAD

**Issue by danyalaytekin** [aleclarson/emitter-kit#17]
# Environment

Xcode 6.3 (6D570)
OS X 10.10.3
Building for iPhone 6 (8.1, 8.3)

# Setup

Added `emitter-kit` as a submodule to the project.  I am not using CocoaPods due to various problems experienced earlier.

# Error

When compiling, receive the error `Unknown type name 'FOUNDATION_EXPORT'`.

## Error screenshots

![image](https://cloud.githubusercontent.com/assets/1315042/7961009/a276a798-09fc-11e5-8f4e-3fe7086dc72c.png)

![image](https://cloud.githubusercontent.com/assets/1315042/7961017/b155a7be-09fc-11e5-9060-0df8aed98d44.png)

# Workaround

The project builds successfully if each occurrence of `FOUNDATION_EXPORT` is changed to `extern`.

**Comment by aleclarson** [comment]
Whoops, thanks for letting me know! :+1:

**Comment by danyalaytekin** [comment]
Thanks, that was super quick. Is it worth adding your repo to something like Travis, which would have caught this issue early? http://docs.travis-ci.com/user/languages/objective-c/

**Comment by dkun7944** [comment]
@aleclarson How did you fix this issue? Having the same problem in a project of mine.

**Comment by aleclarson** [comment]
@dkun7944 

This was fixed by adding `#import <Foundation/Foundation.h>` to `EmitterKit.h`.

As evidenced by [this StackOverflow question](http://stackoverflow.com/questions/10953221/foundation-export-vs-extern), it seems `extern` would also work.

Are you getting the same error? Which version of `emitter-kit` are you using?
