### ISSUE TITLE
notification + target seems to not be working

### ISSUE THREAD

**Issue by mateusmaso** [aleclarson/emitter-kit#23]
works:
```swift
NSNotificationCenter.defaultCenter().addObserverForName(NSPopoverWillCloseNotification, object: self.popover, queue: nil, usingBlock: { _ in
  self.statusItemView.highlighted = false
})
```

don't work:
```swift
Notification(NSPopoverWillCloseNotification).on(self.popover, { data in
  self.statusItemView.highlighted = false
})
```

am I doing something wrong?

**Comment by aleclarson** [comment]
```Swift
// In the class declaration:
//
var listeners = [Listener]()


// In one of the class's methods:
//
self.listeners += Notification(NSPopoverWillCloseNotification).on(self.popover) {
  [unowned self] data in
  self.statusItemView.highlighted = false
}
```

If you don't retain the returned `Listener`, it will deinit before it can "hear" the emitted `NSNotification`.

Also, notice the `[unowned self]` that I added. This prevents a memory leak, but there's a catch. You must make sure the returned `Listener` deinits before `self` does. Otherwise, your program will crash when trying to access `self` after hearing the emitted `NSNotification`.

Hope that all makes sense. Cheers!
