### ISSUE TITLE
Prevent retain cycles

### ISSUE THREAD

**Issue by Zyphrax** [aleclarson/emitter-kit#40]
Working with the Event class I often have to make sure that I'm not creating a retain cycle.
To make it a bit easier, I've created the following helper:

```swift
func on<Owner: AnyObject>(_ owner: Owner, _ method: @escaping (Owner) -> (T) -> Void) -> EventListener<T> {
  return self.on { [weak owner] data in
    if let ownerRef = owner {
      method(ownerRef)(data)
    }
  }
}
```

You can use it like this:

```swift
var listener = myEvent.on(self, MyClass.onMyEvent)

private func onMyEvent(data: Data) {
  print(data)
}
```

Would you consider adding this to the codebase?

Perhaps the method should have a different name than `on` to prevent confusion with the overloads that have the targetting arguments.

**Comment by aleclarson** [comment]
Thanks for opening an issue! I'm a little confused about your use case here.

In your scenario, is `owner` retaining both `listener` and `myEvent`.

If the `owner` is only retaining `myEvent`, no retain cycle occurs.

If the `owner` is retaining `listener` (and the listener is referencing the owner), you'll want to use `weak owner` to prevent a retain cycle. If the `owner` is also retaining `myEvent`, you can use `unowned owner`, because the `listener` will be deallocated when `myEvent` is deallocated (as long as no other instance has a strong reference to `listener`).

Just remember that you're not required to retain `listener` since `myEvent` will do that for you. The only time you'd want to retain `listener` is to stop it manually or because `myEvent` is used between multiple instances (which doesn't work well since you'll be forced to stop each listener manually).

Let me know if none of that helps you. Although, I recommend the `owner` retains at least one of `myEvent` or `listener`, but maybe I'm not seeing a legitimate use case to not do so.

**Comment by Zyphrax** [comment]
It is actually a sort of poor-man's delegate implementation.

With the `on` function you risk creating a retain cycle if you use `self`, because `self` retains the `listener` and the block is retaining `self` (if you don't use weak).

One option is to do this:

```swift
self.listener = myEvent.on { [weak self] data in {
  guard let me = self else { return }
  ...
}
```

If your handler is a bit more complicated, and you move it to a function, some people might do this:

```swift
self.listener = myEvent.on(onMyEvent)

private func onMyEvent(data: Data) {
  print(data)
}
```

Which is really risky, because you are actually creating a retain cycle, but it isn't that visible.

In Swift you can call a instance function statically by providing `self` as the first argument. My helper makes it easier to call a handler function without risking a retain cycle.

**Comment by Mattijah** [comment]
Actually, rather than using `[weak self]` (`weak owner`), you should be using `[unowned self]` here.

```swift
listener = myEvent.on({ [unowned self] in self.onMyEvent($0) })
```

not far from something like:

```swift
listener = myEvent.on(owner: self, handler: onMyEvent)
```

`If your handler is a bit more complicated, and you move it to a function, some people might do this...`

I think the people you are talking about would probably still do this even if this library would contain the method you are suggesting to have.

**Comment by mingsai** [comment]
> Actually, rather than using `[weak self]` (`weak owner`), you should be using `[unowned self]` here.
> 
> ```swift
> listener = myEvent.on({ [unowned self] in self.onMyEvent($0) })
> ```
> 
> not far from something like:
> 
> ```swift
> listener = myEvent.on(owner: self, handler: onMyEvent)
> 
> //*or maybe just something like this since the listener is tied to the owner:
> myEvent.on(owner: self, handler: onMyEvent)
> ```
> 
> > If your handler is a bit more complicated, and you move it to a function, some people might do this...
> 
> I think the people you are talking about would probably still do this even if this library would contain the method you are suggesting to have.

Just a quick note on `[unowned self]` usage here. It is quite possible that the owner may be nil as in objects that have passed beyond the current frame. I think weak would be a safer route. I do agree that if one is likely to miss the opportunity for a retain cycle then adding more stuff to the library seems unnecessary. With that in mind, I'm not sure why a help requested tag is still on this 'enhancement'?
